rvm: 
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
notifications:
  email:
    - inkblot@movealong.org
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
